CREATE TABLE PROFESION (
	COD_PROF INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PAIS (
	COD_PAIS INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PUESTO (
	COD_PUESTO INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE DEPARTAMENTO (
	COD_DEPTO INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MIEMBRO (
	COD_MIEMBRO INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	EDAD INTEGER NOT NULL,
	TELEFONO INTEGER,
	RESIDENCIA VARCHAR(100),
	PAIS_COD_PAIS INTEGER NOT NULL, 
	CONSTRAINT FK_M1 FOREIGN KEY (PAIS_COD_PAIS) REFERENCES PAIS(COD_PAIS),
	PROFESION_COD_PROF INTEGER NOT NULL, 
	CONSTRAINT FK_M2 FOREIGN KEY (PROFESION_COD_PROF) REFERENCES PROFESION(COD_PROF)	
);

CREATE TABLE PUESTO_MIEMBRO (
	MIEMBRO_COD_MIEMBRO INTEGER NOT NULL,
	PUESTO_COD_PUESTO INTEGER NOT NULL,
	DEPARTAMENTO_COD_DEPTO INTEGER NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE,
	CONSTRAINT PF_PM PRIMARY KEY (MIEMBRO_COD_MIEMBRO, PUESTO_COD_PUESTO, DEPARTAMENTO_COD_DEPTO),
	CONSTRAINT FK_PM1 FOREIGN KEY (MIEMBRO_COD_MIEMBRO) REFERENCES MIEMBRO(COD_MIEMBRO),
	CONSTRAINT FK_PM2 FOREIGN KEY (PUESTO_COD_PUESTO) REFERENCES PUESTO(COD_PUESTO),
	CONSTRAINT FK_PM3 FOREIGN KEY (DEPARTAMENTO_COD_DEPTO) REFERENCES DEPARTAMENTO(COD_DEPTO)	
);

CREATE TABLE TIPO_MEDALLA (
	COD_TIPO INTEGER NOT NULL PRIMARY KEY,
	MEDALLA VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE MEDALLERO (
	PAIS_COD_PAIS INTEGER NOT NULL,
	CANTIDAD_MEDALLAS INTEGER NOT NULL,
	TIPO_MEDALLA_COD_TIPO INTEGER NOT NULL,
	CONSTRAINT PF_MED PRIMARY KEY (PAIS_COD_PAIS, TIPO_MEDALLA_COD_TIPO),
	CONSTRAINT FK_MED1 FOREIGN KEY (PAIS_COD_PAIS) REFERENCES PAIS(COD_PAIS),
	CONSTRAINT FK_MED2 FOREIGN KEY (TIPO_MEDALLA_COD_TIPO) REFERENCES TIPO_MEDALLA(COD_TIPO)
);

CREATE TABLE DISCIPLINA (
	COD_DISCIPLINA INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(150)
);

CREATE TABLE ATLETA (
	COD_ATLETA INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	EDAD INTEGER NOT NULL,
	PARTICIPACIONES VARCHAR(100) NOT NULL,
	DISCIPLINA_COD_DISCIPLINA INTEGER NOT NULL,
	CONSTRAINT FK_AT1 FOREIGN KEY (DISCIPLINA_COD_DISCIPLINA) REFERENCES DISCIPLINA(COD_DISCIPLINA),
	PAIS_COD_PAIS INTEGER NOT NULL,
	CONSTRAINT FK_AT2 FOREIGN KEY (PAIS_COD_PAIS) REFERENCES PAIS(COD_PAIS)	
);

CREATE TABLE CATEGORIA (
	COD_CATEGORIA INTEGER NOT NULL PRIMARY KEY,
	CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE TIPO_PARTICIPACION (
	COD_PARTICIPACION INTEGER NOT NULL PRIMARY KEY,
	TIPO_PATICIPACION VARCHAR(100) NOT NULL
);

CREATE TABLE EVENTO (
	COD_EVENTO INTEGER NOT NULL PRIMARY KEY,
	FECHA DATE NOT NULL,
	UBICACION VARCHAR(50) NOT NULL,
	HORA DATE NOT NULL,
	DIS_COD_DISCIPLINA INTEGER NOT NULL,
	CONSTRAINT FK_EV1 FOREIGN KEY (DIS_COD_DISCIPLINA) REFERENCES DISCIPLINA(COD_DISCIPLINA),
	TP_COD_PARTICIPACION INTEGER NOT NULL,
	CONSTRAINT FK_EV2 FOREIGN KEY (TP_COD_PARTICIPACION) REFERENCES TIPO_PARTICIPACION(COD_PARTICIPACION),
	CATEGORIA_COD_CATEGORIA INTEGER NOT NULL,
	CONSTRAINT FK_EV3 FOREIGN KEY (CATEGORIA_COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA)
);

CREATE TABLE EVENTO_ATLETA (
	ATLETA_COD_ATLETA INTEGER NOT NULL,
	EVENTO_COD_EVENTO INTEGER NOT NULL,
	CONSTRAINT PF PRIMARY KEY (ATLETA_COD_ATLETA, EVENTO_COD_EVENTO),
	CONSTRAINT FK_EA1 FOREIGN KEY (ATLETA_COD_ATLETA) REFERENCES ATLETA(COD_ATLETA),
	CONSTRAINT FK_EA2 FOREIGN KEY (EVENTO_COD_EVENTO) REFERENCES EVENTO(COD_EVENTO)
);

CREATE TABLE TELEVISORA (
	COD_TELEVISORA INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE COSTO_EVENTO (
	EVENTO_COD_EVENTO INTEGER NOT NULL,
	TELEVISORA_COD_TELEVISORA INTEGER NOT NULL,
	TARIFA INTEGER NOT NULL,
	CONSTRAINT PF_CE PRIMARY KEY (EVENTO_COD_EVENTO, TELEVISORA_COD_TELEVISORA),
	CONSTRAINT FK_CE1 FOREIGN KEY (EVENTO_COD_EVENTO) REFERENCES EVENTO(COD_EVENTO),
	CONSTRAINT FK_CE2 FOREIGN KEY (TELEVISORA_COD_TELEVISORA) REFERENCES TELEVISORA(COD_TELEVISORA)
);